// !!! BELOW I IMPORT ALL OF DEPENDENCIES !!!  and other useful stuff// 

import { ClerkProvider, UserButton, auth, currentUser } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link"


// !!! REST OF A CODE BELOW !!! //

//metadata:
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "week 12 project",  // This is temporary name //
  description: "Generated by create next app",
};


// default async function:
export default async function RootLayout({ children }) { // START of a function RootLayout //

// Getting userId from auth() -- user is not logged in when null//
      const { userId } = auth();
      console.log("userID:", userId); // This is to check userID in console and if he logged in //

      // Get the BackEnd API object when we need access to the user's info //
      const users = await currentUser();
      console.log("User:", users)


  return (  // START of returning in RootLayout //

  <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <h6>This is our final project</h6>
        <nav>
            <Link classname="homepage" href="/">Week 12</Link>
            {userId && <UserButton ID = "userbutton" afterSignOutUrl="/" />}
            {userId && <Link href = "/sign-in">Sign in</Link>}

        </nav>
      <h5>
       <Link href="/">HOME</Link>
       <Link href="/Posts">MAIN</Link>
       <Link href="/UserPosts">USER'S POSTS</Link>
       </h5>
       
       {children}
       </body>
    </html>
  </ClerkProvider>

  ); // END of returning in RootLayout //
}; // END of a function RootLayout //
